// local config
export const SAVE_SERVER_ADDRESS_CHANGEABLE = 'SAVE_SERVER_ADDRESS_CHANGEABLE';
export const SAVE_SERVER_ADDRESS = 'SAVE_SERVER_ADDRESS';
export const SAVE_MODE = 'SAVE_MODE';
export const SAVE_CITY = 'SAVE_CITY';

// user
export const GET_VCODE = 'GET_VCODE';
export const GET_LOGIN_VERIFICATION = 'GET_LOGIN_VERIFICATION';
export const GET_BIND_PHONE_SEND = 'GET_BIND_PHONE_SEND';
export const GET_BIND_PHONE_VERIFY = 'GET_BIND_PHONE_VERIFY';
export const CHECK_USER = 'CHECK_USER';
export const REGISTER = 'REGISTER';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const GET_USER_FROM_STORAGE = 'GET_USER_FROM_STORAGE';
export const UPDATE_CLIENT_USER_INFO = 'UPDATE_CLIENT_USER_INFO';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_BACKEND = 'LOGOUT_BACKEND';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const GET_USER_INFO = 'GET_USER_INFO';
export const CHANGE_USER_PASSWD = 'CHANGE_USER_PASSWD';
export const RESET_USER_PASSWD = 'RESET_USER_PASSWD';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CLEAR = 'CLEAR';
export const SAVE_USER_PHONE = 'SAVE_USER_PHONE';
export const GET_BACKEND_VERSION = 'GET_BACKEND_VERSION';
export const SAVE_SEARCHER_HISTORYS = 'SAVE_SEARCHER_HISTORYS';
export const GET_USER_CHANGE_DEV_OWNER_VERIFICATION = 'GET_USER_CHANGE_DEV_OWNER_VERIFICATION';
export const GET_USER_FORGETPASSWD_VERIFICATION = 'GET_USER_FORGETPASSWD_VERIFICATION';
export const CHANGE_USER_HEADIMAGE = 'CHANGE_USER_HEADIMAGE';
export const CHANGE_USER_ADDR = 'CHANGE_USER_ADDR';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';
export const EMAIL_SEND = 'EMAIL_SEND';
export const LOGIN_CODE = 'LOGIN_CODE';

// user 本地修改
export const UPDATE_USER_NAME_LOCAL = 'UPDATE_USER_NAME_LOCAL';
export const UPDATE_USER_ADDR_LOCAL = 'UPDATE_USER_ADDR_LOCAL';
export const UPDATE_USER_EMAIL_LOCAL = 'UPDATE_USER_EMAIL_LOCAL';
export const UPDATE_USER_HEAD_IMAGE_LOCAL = 'UPDATE_USER_HEAD_IMAGE_LOCAL';
export const UPDATE_USER_PHONE_LOCAL = 'UPDATE_USER_PHONE_LOCAL';

// utils
export const TOAST = 'TOAST';
export const FORBIDDEN403 = 'FORBIDDEN403';
export const OPEN_TOAST = 'OPEN_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';

// middleware
export const SYNC_REDUCER_TO_ASYNC_STORAGE = 'SYNC_REDUCER_TO_ASYNC_STORAGE';
export const GET_REDUCER_FROM_ASYNC_STORAGE = 'GET_REDUCER_FROM_ASYNC_STORAGE';
export const CAN_OPEN_URL = 'CAN_OPEN_URL';
export const LAYOUT = 'LAYOUT';
