module.exports = function (sequelize, DataTypes) {
  return sequelize.define(
    'b_user',
    {
      id: {
        type: DataTypes.BIGINT,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      status: {
        type: DataTypes.INTEGER(11),
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      phone: {
        type: DataTypes.STRING,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      id_number: {
        type: DataTypes.STRING,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      email: {
        type: DataTypes.STRING,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      addr: {
        type: DataTypes.STRING,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      tdate: {
        type: DataTypes.DATE,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      type: {
        type: DataTypes.INTEGER(11),
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      headimage: {
        type: DataTypes.STRING,
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: null,
      },
      freeCnt: {
        type: DataTypes.INTEGER(11),
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: 0,
      },
      push_id: {
        type: DataTypes.STRING,
        allowNull: true,
        defaultValue: null,
      },
      push_tag: {
        //JSON
        type: DataTypes.STRING,
        allowNull: true,
        defaultValue: '[]',
      },
      free_cost: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: true,
        autoIncrement: false,
        primaryKey: false,
        defaultValue: 0,
      },
      referral_code: {
        comment: '产品编码/分享码',
        type: DataTypes.STRING(5),
        allowNull: true,
        defaultValue: null,
        unique: true,
      },
    },
    {
      tableName: 'b_user',
      charset: 'utf8mb4',
      collate: 'utf8mb4_general_ci',
    },
  );
};
